/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AttendanceTracker;


public class App {

    public static void main(String[] args) {
        StartUp.displayTitle();
        
    }
}

