/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package AttendanceTracker;
//
//
//import static AttendanceTracker.AbsentStudent.userChooseStudentSelection;
//import static AttendanceTracker.YearOptions.userChooseYearStyle;
//
//public class App {
//
//    public static void main(String[] args) {
//
//        userChooseYearStyle();
//
//        userChooseStudentSelection();
//    }
//
//
//}
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package AttendanceTracker;
import java.time.Year;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {

    static void StartUp(){
        StartUp.displayTitle();
    }

    static void Preview(){
        YearOptions.userChooseYearStyle();
        SemesterOptions.displaySemestersFromMap(SemesterOptions.semesters);

        int choice = SemesterOptions.promptUserforSemester(SemesterOptions.semesters);
        String enteredSemester;
        if(choice != 0){
            enteredSemester = SemesterOptions.selectSemester(SemesterOptions.semesters, choice);
            System.out.println("Entered Semester is: " + enteredSemester);
        } else {
            enteredSemester = SemesterOptions.selectDefaultSemester(SemesterOptions.semesters);
            System.out.println("Entered Semester is: " + enteredSemester);
        }

    }

    public static void main(String[] args) {
        App.StartUp();
        App.Preview();
    }

}