/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AttendanceTracker;

import static AttendanceTracker.UserChooseYear.userChooseYearStyle;

public class App {

    public static void main(String[] args) {
        userChooseYearStyle();
    }


}

